name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      uses: appleboy/ssh-action@main

      with:

        host: ${{ secrets.ADMIN_SITE_SERVER }}

        key: ${{ secrets.ADMIN_SITE_KEY }}

        username: ${{ secrets.ADMIN_SITE_USER }}

        script: |

          cd /var/www/html/
          
          git pull
          
          git merge
          
          php artisan migrate --force
          
          echo 'Completed'
          
          
          
  
