name: Laravel

on:
  push:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LARAVEL_SITE_SERVER }}
          key: ${{ secrets.ADMIN_SITE_KEY }}
          username: ${{ secrets.ADMIN_SITE_USER }}
          script: |
            
            cd /var/www/html/
            
            git pull
            
            git merge
            
            php artisan migrate --force
            
            echo 'Completed'
