name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2

    - name: Remove Composer Lock
      run: php -r "file_exists('composer.lock');"
      
    - name: Remove Package Lock
      run: php -r "file_exists('package-lock.json');"
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.16'

    - name: Install Composer
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Update Composer 
      run: composer update --no-interaction --prefer-dist --optimize-autoloader
    
    - name: Remove Storage Logs
      run: php -r "file_exists('storage/logs/*.log');"
      
    - name: Remove Storage Debug Logs
      run: php -r "file_exists('storage/debugbar/*.json');"
      
    #- name: Artisan Optimization
     # run: php artisan optimize
      
    - name: Composer Dump Autoload
      run: composer dump-autoload -o
      
    - name: Queue Restart
      run: php artisan queue:restart
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
          username: '${{ secrets.ADMIN_SITE_USER}}'
          server: '${{ secrets.LARAVEL_SITE_SERVER}}'
          ssh_private_key: ${{ secrets.ADMIN_SITE_KEY }}
          remote_path: '/var/www/html/'
          args: '-o ConnectTimeout=5'
          
          
          
  
